# Worker — Background processor consuming RabbitMQ messages
# Internal only, no service endpoint needed (it pulls from queue)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: contoso-insurance
  labels:
    app: worker
    app.kubernetes.io/part-of: contoso-insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      nodeSelector:
        workload: contoso-insurance
      containers:
        - name: worker
          image: __ACR_LOGIN_SERVER__/contoso-insurance/worker:__TAG__
          env:
            - name: ConnectionStrings__insurancedb
              valueFrom:
                secretKeyRef:
                  name: contoso-secrets
                  key: SQL_CONNECTION_STRING
            - name: ConnectionStrings__messaging
              valueFrom:
                secretKeyRef:
                  name: contoso-secrets
                  key: RABBITMQ_CONNECTION_STRING
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: contoso-config
                  key: APPLICATIONINSIGHTS_CONNECTION_STRING
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
