apiVersion: v1
kind: Secret
metadata:
  name: contoso-secrets
  namespace: __NAMESPACE__
type: Opaque
stringData:
  ConnectionStrings__insurancedb: "__SQL_CONNECTION_STRING__"
  RABBITMQ_USERNAME: "__RABBITMQ_USERNAME__"
  RABBITMQ_PASSWORD: "__RABBITMQ_PASSWORD__"
  AzureAd__ClientSecret: "__BACKEND_PORTAL_AZURE_AD_CLIENT_SECRET__"
---
apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-admin
  namespace: __NAMESPACE__
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: "__SQL_SA_PASSWORD__"
